function wine = wineConfig

wine.dataPath = 'C:\Work\GitHub\wine_classification\example_data';
if ~exist(wine.dataPath,"dir")
    wine.dataPath = 'M:\GitHub\wine_classification\example_data';
end

% Atributte's names intended to be used in the data table
wine.attribute.fieldNames = {
    'alcohol',...         % 	1) Alcohol
    'malicAcid',...       % 	2) Malic acid
    'ash',...             % 	3) Ash
    'ashAlcalinity',...   %   4) Alcalinity of ash  
    'magnesium',...       % 	5) Magnesium
    'phenols',...         %   6) Total phenols
    'flavanoids',...      % 	7) Flavanoids
    'nonFlavanoids',...   % 	8) Nonflavanoid phenols
    'proanthocyanins',... % 	9) Proanthocyanins
    'color',...           %   10) Color intensity
    'hue',...             % 	11) Hue
    'odRatio',...         % 	12) OD280/OD315 of diluted wines
    'proline',...         % 	13) Proline  
    };

% Atributte's labels intended to be used in plots
wine.attribute.labels = {
    'Alcohol',...         
    'Malic acid',...       
    'Ash',...             
    'Alcalinity of ash',...     
    'Magnesium',...       
    'Total phenols',...         
    'Flavanoids',...      
    'Nonflavanoid phenols',...   
    'Proanthocyanins',... 	
    'Color intensity',...           
    'Hue',...             	
    'OD280/OD315',...         
    'Proline',...          
    };

wineMatrix = importdata(fullfile(wine.dataPath,'wine.data'));
wine.id = wineMatrix(:,1);
wine.data = array2table(wineMatrix(:,2:14),...
    "VariableNames",wine.attribute.fieldNames);
wine.chemical = wine.data(:,1:9);